### ISSUE TITLE
Cant use objects at all

### ISSUE THREAD

**Issue by SleepyCatOfficial** [lstwo/ShadowLib#1]
when using the mods Console Commands and QuickClip, i cannot interact at all with the cars, houses, etc...

**Comment by SleepyCatOfficial** [comment]
and also ServerUtils

**Comment by lstwo** [comment]
do you have shadowlib installed? if yes could you provide log details? you can enable the log in BepInEx/config/BepInEx.cfg and changing Enabled under Logging.Console to true.

**Comment by lstwo** [comment]
i tried recreating the mods you mentioned with dependencies and i could not recreate your issue. maybe you haven't updated shadowlib correctly when updating server util or downloading quicklip
